---
# tasks file for mapr_authtest

- name: check that maprlogin has been run successfully
  sudo: yes
  sudo_user: '{{mapr_admin_username}}'
  command: maprlogin authtest
  register: authtest
  ignore_errors: yes
  changed_when: false

- name: fail if authtest failed
  assert:
    that: authtest.rc == 0
