---
# tasks file for mapr_authtest

- name: check that maprlogin has been run successfully
  sudo_user: mapr
  command: maprlogin authtest
  register: authtest
  ignore_errors: yes

- name: fail if authtest failed
  assert:
    that: authtest.rc == 0
